name: Build conda environment

on:
  workflow_call:

jobs:
  build-env:
    name: Tests - Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure environment with Python ${{ matrix.python-version}}
      if: runner.os != 'Windows'
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.8-0'
        environment-file: ci_environment.yaml
        create-args: >-
          python=${{ matrix.python-version }}
          lalsuite
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Configure environment with Python ${{ matrix.python-version}} (Windows)
      if: runner.os == 'Windows'
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.8-0'
        environment-file: ci_environment.yaml
        create-args: >-
          python=${{ matrix.python-version }}
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Install nessai
      run: |
        pip install . --no-deps
      shell: bash -el {0}
    - name: Set MPL backend on Windows
      if: runner.os == 'Windows'
      run: |
        echo "MPLBACKEND=agg" >> $env:GITHUB_ENV
    - name: Print environment variables
      run: |
        env
